
/**
 * Service de nettoyage et normalisation du contenu
 */

export interface PreprocessOptions {
  preserveFormatting?: boolean;
  cleanMetadata?: boolean;
  convertCallouts?: boolean;
  normalizeLineBreaks?: boolean;
  conservative?: boolean;
  preserveTables?: boolean;
}

export class ContentCleaner {
  /**
   * Préserve les tableaux Markdown
   */
  static preserveMarkdownTables(content: string): string {
    // Détecter et préserver les tableaux Markdown
    return content.replace(
      /((?:\|[^|\n]*)+\|[\n\r]*)+/g,
      (tableMatch) => {
        const lines = tableMatch.split(/[\n\r]+/).filter(line => line.trim());
        return lines
          .map(line => {
            // Nettoyer les espaces autour des pipes tout en préservant la structure
            return line.replace(/\s*\|\s*/g, ' | ').replace(/^\s*\|\s*/, '| ').replace(/\s*\|\s*$/, ' |');
          })
          .join('\n') + '\n';
      }
    );
  }

  /**
   * Vérifie si une ligne fait partie d'un tableau Markdown
   */
  static isTableLine(line: string): boolean {
    return /^\s*\|.*\|\s*$/.test(line) || /^\s*\|[\s-:]*\|\s*$/.test(line);
  }

  /**
   * Nettoie les métadonnées de manière conservatrice
   */
  static cleanMetadataConservative(content: string): string {
    return content
      // Supprimer seulement les timestamps d'export évidents
      .replace(/^Exported on \d{4}-\d{2}-\d{2}.*$/gm, '')
      .replace(/^Generated by .* on \d{4}-\d{2}-\d{2}.*$/gm, '')
      // Nettoyer les espaces excessifs seulement
      .replace(/\n{4,}/g, '\n\n\n')
      .trim();
  }

  /**
   * Normalise les sauts de ligne de manière conservatrice en préservant les tableaux
   */
  static normalizeLineBreaksConservative(content: string): string {
    const lines = content.split('\n');
    const result: string[] = [];
    let inTable = false;
    let consecutiveEmptyLines = 0;

    for (let i = 0; i < lines.length; i++) {
      const line = lines[i];
      const isCurrentLineTable = this.isTableLine(line);
      const isNextLineTable = i < lines.length - 1 ? this.isTableLine(lines[i + 1]) : false;

      // Détecter le début/fin d'un tableau
      if (isCurrentLineTable && !inTable) {
        inTable = true;
      } else if (!isCurrentLineTable && !isNextLineTable && inTable) {
        inTable = false;
      }

      if (line.trim() === '') {
        consecutiveEmptyLines++;
        // Dans un tableau, préserver au maximum 1 ligne vide
        if (inTable && consecutiveEmptyLines <= 1) {
          result.push(line);
        }
        // Hors tableau, limiter à 2 lignes vides consécutives
        else if (!inTable && consecutiveEmptyLines <= 2) {
          result.push(line);
        }
      } else {
        consecutiveEmptyLines = 0;
        result.push(line);
      }
    }

    return result.join('\n')
      // Normaliser les fins de ligne
      .replace(/\r\n/g, '\n')
      .replace(/\r/g, '\n');
  }

  /**
   * Nettoie les métadonnées et artifacts d'export (mode normal)
   */
  static cleanMetadata(content: string): string {
    return content
      // Supprimer les timestamps d'export
      .replace(/^Exported on.*$/gm, '')
      .replace(/^Generated by.*$/gm, '')
      .replace(/^Created with.*$/gm, '')
      .replace(/\n{3,}/g, '\n\n')
      .trim();
  }

  /**
   * Normalise les sauts de ligne (mode normal) en préservant les tableaux
   */
  static normalizeLineBreaks(content: string): string {
    const lines = content.split('\n');
    const result: string[] = [];
    let inTable = false;

    for (let i = 0; i < lines.length; i++) {
      const line = lines[i];
      const isCurrentLineTable = this.isTableLine(line);
      const isNextLineTable = i < lines.length - 1 ? this.isTableLine(lines[i + 1]) : false;

      // Détecter le début/fin d'un tableau
      if (isCurrentLineTable && !inTable) {
        inTable = true;
      } else if (!isCurrentLineTable && !isNextLineTable && inTable) {
        inTable = false;
      }

      result.push(line);
    }

    return result.join('\n')
      // Normaliser les fins de ligne
      .replace(/\r\n/g, '\n')
      .replace(/\r/g, '\n')
      // Appliquer les règles normales seulement hors des tableaux
      .replace(/(\n-\s.*)\n\n(\s*-\s)/g, '$1\n$2')
      .replace(/(\n\d+\.\s.*)\n\n(\s*\d+\.\s)/g, '$1\n$2');
  }

  /**
   * Convertit les callouts en format markdown standard
   */
  static convertCallouts(content: string): string {
    return content
      // Convertir les callouts avec émojis
      .replace(/^(\s*)💡\s*(.+)$/gm, '$1> 💡 **Conseil**: $2')
      .replace(/^(\s*)⚠️\s*(.+)$/gm, '$1> ⚠️ **Attention**: $2')
      .replace(/^(\s*)📝\s*(.+)$/gm, '$1> 📝 **Note**: $2')
      .replace(/^(\s*)✅\s*(.+)$/gm, '$1> ✅ **Succès**: $2')
      .replace(/^(\s*)❌\s*(.+)$/gm, '$1> ❌ **Erreur**: $2')
      .replace(/^(\s*)🔍\s*(.+)$/gm, '$1> 🔍 **Inspection**: $2')
      .replace(/^(\s*)NOTE:\s*(.+)$/gm, '$1> 📝 **Note**: $2')
      .replace(/^(\s*)WARNING:\s*(.+)$/gm, '$1> ⚠️ **Attention**: $2')
      .replace(/^(\s*)TIP:\s*(.+)$/gm, '$1> 💡 **Conseil**: $2');
  }

  /**
   * Préserve et améliore le formatage
   */
  static preserveFormatting(content: string): string {
    let processed = content;

    // Préserver les tableaux en premier
    processed = this.preserveMarkdownTables(processed);

    // Améliorer les autres éléments de formatage
    processed = processed
      // Améliorer les listes à puces
      .replace(/^\s*[\*\+\-]\s+/gm, '- ')
      .replace(/```(\w+)?\n([\s\S]*?)\n```/g, (match, lang, code) => {
        return `\`\`\`${lang || ''}\n${code}\n\`\`\``;
      })
      .replace(/^#{1,6}\s+/gm, (match) => match.trim() + ' ')
      .replace(/\[([^\]]+)\]\s*\(\s*([^)]+)\s*\)/g, '[$1]($2)');

    return processed;
  }

  /**
   * Conversion spécifique pour les exports Claude.ai (mode conservateur)
   */
  static processClaudeExport(content: string): string {
    return content
      // Préserver les blockquotes Claude sans les transformer
      .replace(/^>\s*(.+)$/gm, '> $1')
      // Améliorer les listes de tâches seulement si elles sont malformées
      .replace(/^-\s*\[\s*\]\s*(.+)$/gm, '- [ ] $1')
      .replace(/^-\s*\[x\]\s*(.+)$/gm, '- [x] $1');
  }
}
