
/**
 * Service de nettoyage et normalisation du contenu
 */

export interface PreprocessOptions {
  preserveFormatting?: boolean;
  cleanMetadata?: boolean;
  convertCallouts?: boolean;
  normalizeLineBreaks?: boolean;
  conservative?: boolean;
}

export class ContentCleaner {
  /**
   * Nettoie les métadonnées de manière conservatrice
   */
  static cleanMetadataConservative(content: string): string {
    return content
      // Supprimer seulement les timestamps d'export évidents
      .replace(/^Exported on \d{4}-\d{2}-\d{2}.*$/gm, '')
      .replace(/^Generated by .* on \d{4}-\d{2}-\d{2}.*$/gm, '')
      // Nettoyer les espaces excessifs seulement
      .replace(/\n{4,}/g, '\n\n\n')
      .trim();
  }

  /**
   * Normalise les sauts de ligne de manière conservatrice
   */
  static normalizeLineBreaksConservative(content: string): string {
    return content
      // Normaliser les fins de ligne seulement
      .replace(/\r\n/g, '\n')
      .replace(/\r/g, '\n')
      // Réduire les sauts de ligne excessifs (4+ vers 2)
      .replace(/\n{4,}/g, '\n\n');
  }

  /**
   * Nettoie les métadonnées et artifacts d'export (mode normal)
   */
  static cleanMetadata(content: string): string {
    return content
      // Supprimer les timestamps d'export
      .replace(/^Exported on.*$/gm, '')
      .replace(/^Generated by.*$/gm, '')
      .replace(/^Created with.*$/gm, '')
      .replace(/\n{3,}/g, '\n\n')
      .trim();
  }

  /**
   * Normalise les sauts de ligne (mode normal)
   */
  static normalizeLineBreaks(content: string): string {
    return content
      // Normaliser les fins de ligne
      .replace(/\r\n/g, '\n')
      .replace(/\r/g, '\n')
      .replace(/(\n-\s.*)\n\n(\s*-\s)/g, '$1\n$2')
      .replace(/(\n\d+\.\s.*)\n\n(\s*\d+\.\s)/g, '$1\n$2');
  }

  /**
   * Convertit les callouts en format markdown standard
   */
  static convertCallouts(content: string): string {
    return content
      // Convertir les callouts avec émojis
      .replace(/^(\s*)💡\s*(.+)$/gm, '$1> 💡 **Conseil**: $2')
      .replace(/^(\s*)⚠️\s*(.+)$/gm, '$1> ⚠️ **Attention**: $2')
      .replace(/^(\s*)📝\s*(.+)$/gm, '$1> 📝 **Note**: $2')
      .replace(/^(\s*)✅\s*(.+)$/gm, '$1> ✅ **Succès**: $2')
      .replace(/^(\s*)❌\s*(.+)$/gm, '$1> ❌ **Erreur**: $2')
      .replace(/^(\s*)🔍\s*(.+)$/gm, '$1> 🔍 **Inspection**: $2')
      .replace(/^(\s*)NOTE:\s*(.+)$/gm, '$1> 📝 **Note**: $2')
      .replace(/^(\s*)WARNING:\s*(.+)$/gm, '$1> ⚠️ **Attention**: $2')
      .replace(/^(\s*)TIP:\s*(.+)$/gm, '$1> 💡 **Conseil**: $2');
  }

  /**
   * Préserve et améliore le formatage
   */
  static preserveFormatting(content: string): string {
    return content
      // Améliorer les listes à puces
      .replace(/^\s*[\*\+\-]\s+/gm, '- ')
      .replace(/```(\w+)?\n([\s\S]*?)\n```/g, (match, lang, code) => {
        return `\`\`\`${lang || ''}\n${code}\n\`\`\``;
      })
      .replace(/^#{1,6}\s+/gm, (match) => match.trim() + ' ')
      .replace(/\[([^\]]+)\]\s*\(\s*([^)]+)\s*\)/g, '[$1]($2)');
  }

  /**
   * Conversion spécifique pour les exports Claude.ai (mode conservateur)
   */
  static processClaudeExport(content: string): string {
    return content
      // Préserver les blockquotes Claude sans les transformer
      .replace(/^>\s*(.+)$/gm, '> $1')
      // Améliorer les listes de tâches seulement si elles sont malformées
      .replace(/^-\s*\[\s*\]\s*(.+)$/gm, '- [ ] $1')
      .replace(/^-\s*\[x\]\s*(.+)$/gm, '- [x] $1');
  }
}
